### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by mastershaig** [natanelia/gsmarena-scraper#4]
Can you help why I am getting this error ? 
```
Skipped:  http://www.gsmarena.com/zte_nubia_z9-7207.php
Scrapping...
Error: No default engine was specified and no extension was provided.
    at new View (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/view.js:62:11)
    at EventEmitter.render (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/application.js:569:12)
    at ServerResponse.render (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/response.js:960:7)
    at /home/barama/Downloads/gsmarena-scraper/index.js:46:7
    at Layer.handle_error (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:310:13)
    at /home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:330:12)
    at next (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/layer.js:73:5)
    at trim_prefix (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:310:13)
    at /home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:330:12)
    at next (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:271:10)
    at /home/barama/Downloads/gsmarena-scraper/index.js:25:3
    at Layer.handle [as handle_request] (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/layer.js:95:5)
Re-caching complete.
Error: No default engine was specified and no extension was provided.
    at new View (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/view.js:62:11)
    at EventEmitter.render (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/application.js:569:12)
    at ServerResponse.render (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/response.js:960:7)
    at /home/barama/Downloads/gsmarena-scraper/index.js:46:7
    at Layer.handle_error (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:310:13)
    at /home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:330:12)
    at next (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:271:10)
    at Layer.handle_error (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/layer.js:73:5)
    at trim_prefix (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:310:13)
    at /home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:330:12)
    at next (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/index.js:271:10)
    at /home/barama/Downloads/gsmarena-scraper/index.js:25:3
    at Layer.handle [as handle_request] (/home/barama/Downloads/gsmarena-scraper/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by natanelia** [comment]
Help me get through. What is your version of Node?

Basically, because I don't use Jade in the script, when trying to render HTML (usually on the event of error), the server is throwing that error message, because it doesn't have template engine (like Jade).

**Comment by mastershaig** [comment]
My Node version is v6.2.2.

Okey, I think it isn`t necessary error, thanks !
